/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import DataTypes.DataRegistro;
import Interfaces.IControlador;
import java.awt.Font;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JSeparator;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author brito
 */
public class InterConsultaSesion extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterConsultaSesion
     */
    private final IControlador ic;
    private DefaultTableModel modeloTabla;
    private List<DataRegistro> registros;
    public InterConsultaSesion(IControlador ic) {
        this.ic = ic;
        this.setTitle("Registro de Acceso a Culturarte Web");
        initComponents();
        inicializarTablas();
        registros = ic.getRegistroSesion();
        registros.sort(Comparator.comparing((DataRegistro data)-> data.getFechaRegistro()).reversed());
        //Con la linea de arriba ordeno los registros por fecha
        llenarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegistros = new javax.swing.JTable();
        JTitulo = new javax.swing.JLabel();
        Separador = new javax.swing.JSeparator();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        tablaRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaRegistros);

        JTitulo.setText(" Registro de Accesos al Sitio Web");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Separador)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                    .addComponent(JTitulo, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(JTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void inicializarTablas(){
        JTitulo.setFont(new Font("Segoe UI", Font.BOLD, 20));
        JTitulo.setHorizontalAlignment(SwingConstants.CENTER);
//
//        JSeparator separador = new JSeparator();
        String[] encabezados = {"#", "IP" , "URL", "Browser","SO","Fecha y Hora"};    
    
        modeloTabla = new DefaultTableModel(encabezados,0){
            @Override
            public boolean isCellEditable(int row,int column){
                return false; //Evito que las celdas se puedan editar
            }
        };
        
        tablaRegistros.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        tablaRegistros.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tablaRegistros.setRowHeight(24);
        tablaRegistros.setAutoCreateRowSorter(true); // permite ordenar clickeando encabezados
        
        tablaRegistros.setModel(modeloTabla);
    
        tablaRegistros.getColumnModel().getColumn(0).setPreferredWidth(30); //ID
        tablaRegistros.getColumnModel().getColumn(1).setPreferredWidth(100); //IP
        tablaRegistros.getColumnModel().getColumn(2).setPreferredWidth(270); //URL
        tablaRegistros.getColumnModel().getColumn(3).setPreferredWidth(100); //Browser
        tablaRegistros.getColumnModel().getColumn(4).setPreferredWidth(100); //Sistema Operativo
        tablaRegistros.getColumnModel().getColumn(5).setPreferredWidth(150); //Fecha y Hora
    
        tablaRegistros.setRowSelectionAllowed(true);
        tablaRegistros.setColumnSelectionAllowed(false);
        tablaRegistros.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        tablaRegistros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
           
    }
    
    private void llenarFormulario(){ //Esta sera la funcion principal de este internalFrame donde lleno el formulario con las cosas ingresadas
        if(registros != null && !registros.isEmpty()){
        Object[] fila;
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        for (DataRegistro data : registros){
            fila = new Object[6];
            fila[0] = data.getId(); 
            fila[1] = data.getIP();
            fila[2] = data.getURL();
            fila[3] = data.getNavegador();
            fila[4] = data.getSO();
            fila[5] = data.getFechaRegistro().format(formato);
            modeloTabla.addRow(fila);
        }
     }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JTitulo;
    private javax.swing.JSeparator Separador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaRegistros;
    // End of variables declaration//GEN-END:variables
}
