/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Interfaces.IControlador;
import static java.awt.image.ImageObserver.HEIGHT;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author mafiu
 */
public class InterSeguirUsuario extends javax.swing.JInternalFrame {

    private final IControlador ic;
    List<String> listaUsuarios;
    /**
     * Creates new form InterSeguirUsuario
     * @param ic
     */
    public InterSeguirUsuario(IControlador ic) {
        this.ic = ic;
        listaUsuarios = ic.getUsuarios();
        initComponents();
        for(String s : listaUsuarios){
            comboSeguidor.addItem(s);
        }
        botonAceptar.setEnabled(false);
        comboSeguir.setEnabled(false);
        this.setTitle("Seguir Usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelSeguidor = new javax.swing.JLabel();
        labelSeguir = new javax.swing.JLabel();
        comboSeguidor = new javax.swing.JComboBox<>();
        comboSeguir = new javax.swing.JComboBox<>();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();

        labelTitulo.setText("Seleccione el usuario Seguidor y a Seguir");

        labelSeguidor.setText("Seguidor");

        labelSeguir.setText("Seguir a");

        comboSeguidor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--" }));
        comboSeguidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeguidorActionPerformed(evt);
            }
        });

        comboSeguir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---" }));
        comboSeguir.setEnabled(false);
        comboSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeguirActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboSeguidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(comboSeguir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSeguidor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelSeguir)))
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCancelar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSeguidor)
                    .addComponent(labelSeguir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboSeguidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSeguir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboSeguidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeguidorActionPerformed
        // TODO add your handling code here:
        int seleccion = comboSeguidor.getSelectedIndex();
        comboSeguir.removeAllItems();
        comboSeguir.addItem("---");
        if(seleccion != 0){
            String seguidor = comboSeguidor.getSelectedItem().toString();
            List<String> listaSeguidos = ic.getSeguidos(seguidor);
            for(String s : this.listaUsuarios){
                if(!listaSeguidos.contains(s)){
                    comboSeguir.addItem(s);
                }
            }
            comboSeguir.removeItem(seguidor);
            comboSeguir.setEnabled(true);
        }else{
            comboSeguir.setEnabled(false);
            botonAceptar.setEnabled(false);
        }
    }//GEN-LAST:event_comboSeguidorActionPerformed

    private void comboSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeguirActionPerformed
        // TODO add your handling code here:
        int seleccion = comboSeguir.getSelectedIndex();
        if(seleccion != 0){
            botonAceptar.setEnabled(true);
        }else{
            botonAceptar.setEnabled(false);
        }
    }//GEN-LAST:event_comboSeguirActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        String nick1 = comboSeguidor.getSelectedItem().toString();
        String nick2 = comboSeguir.getSelectedItem().toString();
        int resultado = ic.seguirUsuario(nick1, nick2);
        if(resultado == 0){
            JOptionPane.showMessageDialog(this, nick1 + " ya sigue a " + nick2 + "!", "Error", HEIGHT); //no deberia llegar nunca aqui
        }else{
            JOptionPane.showMessageDialog(this, nick1 + " ha empezado a seguir a " + nick2 + "!", "Listo!", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_botonAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JComboBox<String> comboSeguidor;
    private javax.swing.JComboBox<String> comboSeguir;
    private javax.swing.JLabel labelSeguidor;
    private javax.swing.JLabel labelSeguir;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
