/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Interfaces.IControlador;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SpinnerDateModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author nahud
 */
public class InterAltaUsuario extends javax.swing.JInternalFrame {

    String txtImagen = "";
    List <String> nicksProhibidos = new ArrayList<>(List.of("--Seleccionar--", "---"));
    private final IControlador ic;
    /**
     * Creates new form InterAltaUsuario
     * @param ic
     */
    public InterAltaUsuario(IControlador ic) {
        this.ic = ic;
        initComponents();
        this.textImagenLista.setVisible(false);
        this.panelProp.setVisible(false);
        this.setTitle("Alta Usuario");
        
      //forma manual de cambiar modelo fecha spinner
//        JSpinner.DateEditor editor = new JSpinner.DateEditor(spinnerFecNac, "d/M/yyyy");
//        spinnerFecNac.setEditor(editor);

        //fecha minima de nacimiento (el año de la pepa)
        LocalDate fechaMin = LocalDate.of(1900, 1, 1);
        Date minDate = Date.from(fechaMin.atStartOfDay(ZoneId.systemDefault()).toInstant());

        //fecha maxima de nacimiento (no podes nacer mañana)
        LocalDate fechaMax = LocalDate.now();
        Date maxDate = Date.from(fechaMax.atStartOfDay(ZoneId.systemDefault()).toInstant());

        //fecha inicial (fecha random no importa)
        LocalDate fechaInicial = LocalDate.of(2005, 1, 1);
        Date initialDate = Date.from(fechaInicial.atStartOfDay(ZoneId.systemDefault()).toInstant());

        SpinnerDateModel model = new SpinnerDateModel(initialDate, minDate, maxDate, Calendar.DAY_OF_MONTH);
        spinnerFecNac.setModel(model);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipoUsuario = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelNickname = new javax.swing.JLabel();
        textoNickname = new javax.swing.JTextField();
        labelTitulo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        textoEmail = new javax.swing.JTextField();
        labelApellido = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        textoApellido = new javax.swing.JTextField();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        labelFecNac = new javax.swing.JLabel();
        rbProponente = new javax.swing.JRadioButton();
        rbColaborador = new javax.swing.JRadioButton();
        spinnerFecNac = new javax.swing.JSpinner();
        botonImagen = new javax.swing.JButton();
        labelImagen = new javax.swing.JLabel();
        textImagenLista = new javax.swing.JLabel();
        textoContra = new javax.swing.JTextField();
        textoConfirmacion = new javax.swing.JTextField();
        labelContraseña = new javax.swing.JLabel();
        labelConfirmacion = new javax.swing.JLabel();
        panelProp = new javax.swing.JPanel();
        textoSitioWeb = new javax.swing.JTextField();
        labelBiografia = new javax.swing.JLabel();
        labelSitioWeb = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        textoDireccion = new javax.swing.JTextField();
        jScrollPaneBio = new javax.swing.JScrollPane();
        textoBiografia = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        labelNickname.setText("Nickname");

        textoNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNicknameActionPerformed(evt);
            }
        });

        labelTitulo.setText("Ingrese los siguientes datos");

        labelNombre.setText("Nombre");

        textoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreActionPerformed(evt);
            }
        });

        textoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoEmailActionPerformed(evt);
            }
        });

        labelApellido.setText("Apellido");

        labelEmail.setText("E-mail");

        textoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoApellidoActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        labelFecNac.setText("Fecha Nacimiento");

        bgTipoUsuario.add(rbProponente);
        rbProponente.setText("Proponente");
        rbProponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbProponenteActionPerformed(evt);
            }
        });

        bgTipoUsuario.add(rbColaborador);
        rbColaborador.setText("Colaborador");
        rbColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbColaboradorActionPerformed(evt);
            }
        });

        spinnerFecNac.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1104544800000L), null, null, java.util.Calendar.DAY_OF_MONTH));
        spinnerFecNac.setEditor(new javax.swing.JSpinner.DateEditor(spinnerFecNac, "d/M/yyyy"));

        botonImagen.setText("Seleccionar");
        botonImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonImagenActionPerformed(evt);
            }
        });

        labelImagen.setText("Foto de perfil (opcional)");

        textImagenLista.setText("Imagen seleccionada!");

        textoContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoContraActionPerformed(evt);
            }
        });

        labelContraseña.setText("Contraseña");

        labelConfirmacion.setText("Confirmación");

        panelProp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        textoSitioWeb.setEnabled(false);
        textoSitioWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoSitioWebActionPerformed(evt);
            }
        });

        labelBiografia.setText("Biografia (opcional)");

        labelSitioWeb.setText("Sitio Web (opcional)");

        labelDireccion.setText("Direccion");

        textoDireccion.setEnabled(false);
        textoDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDireccionActionPerformed(evt);
            }
        });

        textoBiografia.setColumns(20);
        textoBiografia.setRows(5);
        textoBiografia.setEnabled(false);
        jScrollPaneBio.setViewportView(textoBiografia);

        javax.swing.GroupLayout panelPropLayout = new javax.swing.GroupLayout(panelProp);
        panelProp.setLayout(panelPropLayout);
        panelPropLayout.setHorizontalGroup(
            panelPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPropLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panelPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelBiografia)
                        .addComponent(labelDireccion))
                    .addComponent(labelSitioWeb))
                .addGap(18, 18, 18)
                .addGroup(panelPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoDireccion)
                    .addComponent(textoSitioWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneBio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelPropLayout.setVerticalGroup(
            panelPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPropLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDireccion)
                    .addComponent(textoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneBio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBiografia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoSitioWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSitioWeb))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelar)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelImagen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonImagen)
                                .addGap(30, 30, 30)
                                .addComponent(textImagenLista))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelFecNac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerFecNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelNombre)
                                    .addComponent(labelNickname)
                                    .addComponent(labelApellido)
                                    .addComponent(labelEmail)
                                    .addComponent(labelContraseña)
                                    .addComponent(labelConfirmacion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textoConfirmacion)
                                    .addComponent(textoNickname)
                                    .addComponent(textoNombre)
                                    .addComponent(textoApellido)
                                    .addComponent(textoEmail)
                                    .addComponent(textoContra, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(rbProponente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbColaborador)))
                        .addContainerGap(70, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNickname)
                    .addComponent(textoNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelApellido)
                    .addComponent(textoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContraseña))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelConfirmacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFecNac)
                    .addComponent(spinnerFecNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbProponente)
                    .addComponent(rbColaborador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelProp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonImagen)
                    .addComponent(labelImagen)
                    .addComponent(textImagenLista))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoApellidoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_textoApellidoActionPerformed

    private void textoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoEmailActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_textoEmailActionPerformed

    private void textoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_textoNombreActionPerformed

    private void textoNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNicknameActionPerformed
        // TODO add your handling code here:

        //System.out.println(nickname);
    }//GEN-LAST:event_textoNicknameActionPerformed

    private void rbColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbColaboradorActionPerformed
        // TODO add your handling code here:
        if(rbColaborador.isSelected()){
            textoDireccion.setEnabled(false);
            textoBiografia.setEnabled(false);
            jScrollPaneBio.setEnabled(false);
            textoSitioWeb.setEnabled(false);
            panelProp.setVisible(false);
        }
    }//GEN-LAST:event_rbColaboradorActionPerformed

    private void rbProponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbProponenteActionPerformed
        // TODO add your handling code here:
        if(rbProponente.isSelected()){
            textoDireccion.setEnabled(true);
            textoBiografia.setEnabled(true);
            jScrollPaneBio.setEnabled(true);
            textoSitioWeb.setEnabled(true);
            panelProp.setVisible(true);
        }
    }//GEN-LAST:event_rbProponenteActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        String nickname = textoNickname.getText().trim();
        String nombre = textoNombre.getText().trim();
        String apellido = textoApellido.getText().trim();
        String email = textoEmail.getText().trim();
        String pass = textoContra.getText().trim();
        String confirmar = textoConfirmacion.getText().trim();
        Date fecha = (Date) spinnerFecNac.getValue();
        LocalDate fecNac = fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        
        if(nickname.isBlank() || nombre.isBlank() || this.nicksProhibidos.contains(nickname) || apellido.isBlank()){
            JOptionPane.showMessageDialog(this, "Opciones vacias o invalidas!", "Error", HEIGHT);
            return;
        }
        if(email.isBlank() || !email.contains("@") || email.contains(" ") || !email.contains(".")){
            JOptionPane.showMessageDialog(this, "Email no válido!", "Error", HEIGHT);
            return;
        }
        if(pass.isBlank()){
            JOptionPane.showMessageDialog(this, "Debe ingresar una contraseña!", "Error", HEIGHT);
            return;
        }
        if(confirmar.isBlank() || !confirmar.equals(pass)){
            JOptionPane.showMessageDialog(this, "Debe confirmar su contraseña!", "Error", HEIGHT);
            return;
        }
        
        String imagenWeb;
        if(!this.txtImagen.isBlank()){
            imagenWeb = "fotos" + File.separator + this.txtImagen.substring(this.txtImagen.lastIndexOf(File.separator), this.txtImagen.length());
        }else{
            imagenWeb = "";
        }
        
        if(rbProponente.isSelected()){
            String direccion = textoDireccion.getText().trim();
            String biografia = textoBiografia.getText();
            String sitioWeb = textoSitioWeb.getText().trim();

            if(direccion.isBlank() || (!sitioWeb.isBlank() && !sitioWeb.contains("."))){
                JOptionPane.showMessageDialog(this, "Opciones vacias o invalidas!", "Error", HEIGHT);
                return;
            }            
            
            String passHash = BCrypt.hashpw(pass, BCrypt.gensalt());
            int resultado = this.ic.añadirUsuario(nickname, nombre, apellido, email, fecNac, this.txtImagen, passHash, direccion, biografia , sitioWeb, imagenWeb);

            switch(resultado){
                case 0 : JOptionPane.showMessageDialog(this, "Nickname ya existe!", "Error", HEIGHT); break;
                case 1 : {
                    JOptionPane.showMessageDialog(this, "Usuario ha sido ingresado!", "Listo!", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();break;
                }
                case 2 : JOptionPane.showMessageDialog(this, "Email ya existe!", "Error", HEIGHT);break;
            }
        }else if(rbColaborador.isSelected()){
            String passHash = BCrypt.hashpw(pass, BCrypt.gensalt());
            int resultado = this.ic.añadirUsuario(nickname, nombre, apellido, email, fecNac, this.txtImagen, passHash, imagenWeb);

            switch(resultado){
            case 0 : JOptionPane.showMessageDialog(this, "Nickname ya existe!", "Error", HEIGHT);break;
            case 1 : {
                JOptionPane.showMessageDialog(this, "Usuario ha sido ingresado!", "Listo!", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();break;
            }
            case 2 : JOptionPane.showMessageDialog(this, "Email ya existe!", "Error", HEIGHT);break;
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debe elegir tipo de usuario!", "Error", HEIGHT);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void textoSitioWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoSitioWebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoSitioWebActionPerformed

    private void textoDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDireccionActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonImagenActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Buscar imagen");
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imágenes JPG & PNG", "jpg", "png");
        fc.setFileFilter(filtro);
        
        File carpetaDestino = new File("fotos");
        if (!carpetaDestino.exists()) {
            carpetaDestino.mkdirs();
        }
        
        if(fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            File foto = new File(fc.getSelectedFile().toString());
            System.out.println(fc.getSelectedFile().toString());
            File destino = new File(carpetaDestino, foto.getName());
            try {
                Files.copy(foto.toPath(), destino.toPath(), StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException ex) {
                Logger.getLogger(InterAltaPropuesta.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("Imagen copiada en: " + destino.getAbsolutePath());
            this.txtImagen = destino.getAbsolutePath();
            this.textImagenLista.setVisible(true);
        }
    }//GEN-LAST:event_botonImagenActionPerformed

    private void textoContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoContraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipoUsuario;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonImagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneBio;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelBiografia;
    private javax.swing.JLabel labelConfirmacion;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelFecNac;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JLabel labelNickname;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelSitioWeb;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelProp;
    private javax.swing.JRadioButton rbColaborador;
    private javax.swing.JRadioButton rbProponente;
    private javax.swing.JSpinner spinnerFecNac;
    private javax.swing.JLabel textImagenLista;
    private javax.swing.JTextField textoApellido;
    private javax.swing.JTextArea textoBiografia;
    private javax.swing.JTextField textoConfirmacion;
    private javax.swing.JTextField textoContra;
    private javax.swing.JTextField textoDireccion;
    private javax.swing.JTextField textoEmail;
    private javax.swing.JTextField textoNickname;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoSitioWeb;
    // End of variables declaration//GEN-END:variables
}
