/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import DataTypes.DataPropuesta;
import Interfaces.IControlador;
import java.awt.Image;
import static java.awt.image.ImageObserver.HEIGHT;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SpinnerDateModel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author mafiu
 */
public class InterModificarPropuesta extends javax.swing.JInternalFrame {

    private final IControlador ic;
    List<String> listaPropuestas;
    String txtImagen = "";
    /**
     * Creates new form InterModificarPropuesta
     * @param ic
     */
    public InterModificarPropuesta(IControlador ic) {
        this.ic = ic;
        listaPropuestas = ic.getPropuestas();
        initComponents();
        for(String s : listaPropuestas){
            comboPropuestas.addItem(s);
        }
        this.textoNick.setEditable(false);
        this.textoTitulo.setEditable(false);
        this.textoCategoria.setEditable(false);
        this.textoEstado.setEditable(false);
        this.textoDescripcion.setEditable(false);
        this.textoLugar.setEditable(false);
        this.textoMontoEntrada.setEditable(false);
        this.textoMontoTotal.setEditable(false);
        this.textoRetorno.setEditable(false);
        this.textoFecha.setEditable(false);
        this.botonCambioImagen.setVisible(false);
        this.comboEstado.setVisible(false);
        this.comboRetorno.setVisible(false);
        this.botonAceptar.setVisible(false);
        this.botonEditar.setEnabled(false);
        this.spinnerFecha.setVisible(false);
        this.botonCategoria.setVisible(false);

        
//        JSpinner.DateEditor editor = new JSpinner.DateEditor(spinnerFecha, "d/M/yyyy");
//        spinnerFecha.setEditor(editor);

        
        this.setTitle("Modificar Propuesta");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboPropuestas = new javax.swing.JComboBox<>();
        botonEditar = new javax.swing.JButton();
        textoTitulo = new javax.swing.JTextField();
        textoNick = new javax.swing.JTextField();
        textoCategoria = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoDescripcion = new javax.swing.JTextArea();
        textoLugar = new javax.swing.JTextField();
        textoFecha = new javax.swing.JTextField();
        textoMontoEntrada = new javax.swing.JTextField();
        textoMontoTotal = new javax.swing.JTextField();
        textoRetorno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelFoto = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        botonCambioImagen = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        textoEstado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox<>();
        comboRetorno = new javax.swing.JComboBox<>();
        spinnerFecha = new javax.swing.JSpinner();
        botonCategoria = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(670, 570));

        jLabel1.setText("Seleccionar propuesta");

        comboPropuestas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--" }));
        comboPropuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPropuestasActionPerformed(evt);
            }
        });

        botonEditar.setText("Editar");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        textoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTituloActionPerformed(evt);
            }
        });

        textoDescripcion.setColumns(20);
        textoDescripcion.setRows(5);
        jScrollPane1.setViewportView(textoDescripcion);

        jLabel2.setText("Titulo");

        jLabel3.setText("Nickname Prop.");

        jLabel4.setText("Categoria");

        jLabel5.setText("Descripción");

        jLabel6.setText("Lugar");

        jLabel7.setText("Fecha Prevista");

        jLabel8.setText("Monto X Entrada");

        jLabel9.setText("Monto Objetivo");

        jLabel10.setText("Tipo Retorno");

        labelFoto.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        labelFoto.setPreferredSize(new java.awt.Dimension(200, 200));

        jLabel11.setText("Foto");

        botonCambioImagen.setText("Cambiar");
        botonCambioImagen.setEnabled(false);
        botonCambioImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambioImagenActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        textoEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoEstadoActionPerformed(evt);
            }
        });

        jLabel12.setText("Estado");

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingresada", "Publicada", "En financiación", "Financiada", "No financiada", "Cancelada" }));
        comboEstado.setSelectedIndex(-1);
        comboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstadoActionPerformed(evt);
            }
        });

        comboRetorno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entradas Gratis", "% Ventas", "Ambos" }));
        comboRetorno.setSelectedIndex(-1);
        comboRetorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRetornoActionPerformed(evt);
            }
        });

        spinnerFecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1735700400000L), null, null, java.util.Calendar.DAY_OF_MONTH));
        spinnerFecha.setEditor(new javax.swing.JSpinner.DateEditor(spinnerFecha, "d/M/yyyy"));

        botonCategoria.setText("Cambiar");
        botonCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(comboPropuestas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonEditar))
            .addGroup(layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(textoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(textoNick, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel11)
                .addGap(248, 248, 248)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(textoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(botonCategoria))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCambioImagen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel7))
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel9)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(spinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textoMontoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel10)
                .addGap(6, 6, 6)
                .addComponent(textoRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(comboRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(446, 446, 446)
                .addComponent(botonAceptar)
                .addGap(6, 6, 6)
                .addComponent(botonCancelar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(comboPropuestas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEditar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(textoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(textoNick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(textoCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCategoria))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(labelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(botonCambioImagen))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel6)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(textoLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(textoMontoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(textoMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10))
                    .addComponent(textoRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboPropuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPropuestasActionPerformed
        // TODO add your handling code here:
        int op = comboPropuestas.getSelectedIndex();
        String titulo = comboPropuestas.getItemAt(op);
        DataPropuesta DP;
           
        if(op != 0){
            this.botonEditar.setEnabled(true);
            DP = ic.consultaDePropuesta(titulo);

            ImageIcon icon = new ImageIcon(DP.getImagen());

            if(!"".equals(DP.getImagen())){
                Image imagenEscalada = icon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
                labelFoto.setIcon(new ImageIcon(imagenEscalada));
            }

            String retorno = "AMBOS";

            if (DP.getRetorno().toString().equals("ENTRADAS_GRATIS")) {
                retorno = "ENTRADAS GRATIS";
            }
            if (DP.getRetorno().toString().equals("PORCENTAJE_VENTAS")) {
                retorno = "%VENTAS";
            }

            this.textoNick.setText(DP.getProponente().getNickname());
            this.textoTitulo.setText(DP.getTitulo());
            this.textoCategoria.setText(DP.getCategoria());
            this.textoEstado.setText(DP.getEstadoActual().getEstado().toString());
            this.textoDescripcion.setText(DP.getDesc());
            this.textoLugar.setText(DP.getLugar());
            this.textoMontoEntrada.setText(DP.getEntradaa().toString());
            this.textoMontoTotal.setText(DP.getNecesariaa().toString());
            this.textoRetorno.setText(retorno);
            this.textoFecha.setText(DP.getFechaPubli().toString());
            this.txtImagen = DP.getImagen();
            
            //fecha ya establecida de la propuesta
            Date initialDate = Date.from(DP.getFechaPubli().atStartOfDay(ZoneId.systemDefault()).toInstant());
            this.spinnerFecha.setValue(initialDate);
            
            //fecha minima de propuesta (hoy)
            LocalDate fechaMin = LocalDate.of(2017, 1, 1);
            Date minDate = Date.from(fechaMin.atStartOfDay(ZoneId.systemDefault()).toInstant());

            //fecha maxima (jeje)
            LocalDate fechaMax = LocalDate.of(2099, 1, 1);
            Date maxDate = Date.from(fechaMax.atStartOfDay(ZoneId.systemDefault()).toInstant());

            //setea las fechas al spinner
            SpinnerDateModel model = new SpinnerDateModel(initialDate, minDate, maxDate, Calendar.DAY_OF_MONTH);
            spinnerFecha.setModel(model);
            
            String estado = this.textoEstado.getText();
            switch (estado) {
                case "INGRESADA" : this.comboEstado.setSelectedItem("Ingresada"); break;
                case "PUBLICADA" : this.comboEstado.setSelectedItem("Publicada"); break;
                case "EN_FINANCIACION" : this.comboEstado.setSelectedItem("En financiación"); break;
                case "FINANCIADA" : this.comboEstado.setSelectedItem("Financiada"); break;
                case "NO_FINANCIADA" : this.comboEstado.setSelectedItem("No financiada"); break;
                case "CANCELADA" : this.comboEstado.setSelectedItem("Cancelada"); break;
                default : this.comboEstado.setSelectedItem("???");
            }
            
            String ret = this.textoRetorno.getText();
            switch (ret) {
                case "ENTRADAS GRATIS" : this.comboRetorno.setSelectedItem("Entradas Gratis"); break;
                case "%VENTAS" : this.comboRetorno.setSelectedItem("% Ventas"); break;
                case "AMBOS" : this.comboRetorno.setSelectedItem("Ambos"); break;
                default : this.comboRetorno.setSelectedItem("???"); 
            }
        }else{
            this.botonEditar.setEnabled(false);
            this.labelFoto.setIcon(null);
            this.textoNick.setText("");
            this.textoCategoria.setText("");
            this.textoTitulo.setText("");
            this.textoEstado.setText("");
            this.textoDescripcion.setText("");
            this.textoLugar.setText("");
            this.textoMontoEntrada.setText("");
            this.textoMontoTotal.setText("");
            this.textoRetorno.setText("");
            this.textoFecha.setText("");
            this.txtImagen = "";
        }
    }//GEN-LAST:event_comboPropuestasActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        String desc = this.textoDescripcion.getText();
        String lugar = this.textoLugar.getText();
        String montoEntrada = this.textoMontoEntrada.getText();
        String montoObjetivo = this.textoMontoTotal.getText();
        
        if(desc.isBlank() || lugar.isBlank() || montoEntrada.isBlank() || montoObjetivo.isBlank()){
            JOptionPane.showMessageDialog(this, "Opciones vacias!", "Error", HEIGHT);
        }else{
            String titulo = this.textoTitulo.getText();
            String categoria = this.textoCategoria.getText();
            
            int op1 = this.comboEstado.getSelectedIndex();
            String estado = this.comboEstado.getItemAt(op1);
            switch (estado) {
            case "Ingresada" : estado = "INGRESADA"; break;
            case "Publicada" : estado = "PUBLICADA"; break;
            case "En financiación" : estado = "EN_FINANCIACION"; break;
            case "Financiada" : estado = "FINANCIADA"; break;
            case "No financiada" : estado = "NO_FINANCIADA"; break;
            case "Cancelada" : estado = "CANCELADA"; break;
            default : estado = "???";
            };
            
            int op2 = this.comboRetorno.getSelectedIndex();
            String retorno = this.comboRetorno.getItemAt(op2);
            switch (retorno) {
            case "Entradas Gratis" : retorno = "ENTRADAS_GRATIS"; break;
            case "% Ventas" : retorno = "PORCENTAJE_VENTAS"; break;
            case "Ambos" : retorno = "AMBOS"; break;
            default : retorno = "???";
            };
            
            
            Date fec = (Date) this.spinnerFecha.getValue();
            LocalDate fecha = fec.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            
            if(ic.modificarPropuesta(titulo, desc, lugar, fecha, montoEntrada, montoObjetivo, retorno, estado, this.txtImagen, categoria) == 0){
                JOptionPane.showMessageDialog(this, "Propuesta modificada con exito!", "Listo!", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ITS ME ", "ITS ME", HEIGHT);
            }
        }
        
        
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        // TODO add your handling code here:
        this.textoDescripcion.setEditable(true);
        this.textoLugar.setEditable(true);
        this.textoMontoEntrada.setEditable(true);
        this.textoMontoTotal.setEditable(true);
        this.botonCambioImagen.setVisible(true);
        this.botonCambioImagen.setEnabled(true);
        this.botonEditar.setEnabled(false);
        this.botonAceptar.setVisible(true);
        this.botonCategoria.setVisible(true);
        this.comboEstado.setVisible(true);
        this.comboRetorno.setVisible(true);
        this.spinnerFecha.setVisible(true);
        this.comboPropuestas.setEnabled(false);
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonCambioImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambioImagenActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Buscar imagen");
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imágenes JPG & PNG", "jpg", "png");
        fc.setFileFilter(filtro);
        
        File carpetaDestino = new File("fotos");
        if (!carpetaDestino.exists()) {
            carpetaDestino.mkdirs();
        }
        
        if(fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            File foto = new File(fc.getSelectedFile().toString());
            System.out.println(fc.getSelectedFile().toString());
            File destino = new File(carpetaDestino, foto.getName());
            try {
                Files.copy(foto.toPath(), destino.toPath(), StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException ex) {
                Logger.getLogger(InterAltaPropuesta.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("Imagen copiada en: " + destino.getAbsolutePath());
            this.txtImagen = destino.getAbsolutePath();
            
            ImageIcon icon = new ImageIcon(this.txtImagen);

            Image imagenEscalada = icon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            labelFoto.setIcon(new ImageIcon(imagenEscalada));
        }
    }//GEN-LAST:event_botonCambioImagenActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void textoEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoEstadoActionPerformed

    private void comboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstadoActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_comboEstadoActionPerformed

    private void comboRetornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRetornoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRetornoActionPerformed

    private void botonCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCategoriaActionPerformed
        // TODO add your handling code here:
        InterModificarPropuestaCategoria IMPC = new InterModificarPropuestaCategoria(this.ic, this);
        getParent().add(IMPC);
        IMPC.show();
        
        //"esconde" esta ventana y setea en lugar a la seleccion de categoria
        this.setLocation(this.getX(), this.getY()+500);
        int x = (getParent().getWidth() - IMPC.getWidth())/2; //consigue largo de ventana principal
        IMPC.setLocation(x, 100);
    }//GEN-LAST:event_botonCategoriaActionPerformed

    private void textoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTituloActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCambioImagen;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonCategoria;
    private javax.swing.JButton botonEditar;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JComboBox<String> comboPropuestas;
    private javax.swing.JComboBox<String> comboRetorno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JSpinner spinnerFecha;
    private javax.swing.JTextField textoCategoria;
    private javax.swing.JTextArea textoDescripcion;
    private javax.swing.JTextField textoEstado;
    private javax.swing.JTextField textoFecha;
    private javax.swing.JTextField textoLugar;
    private javax.swing.JTextField textoMontoEntrada;
    private javax.swing.JTextField textoMontoTotal;
    private javax.swing.JTextField textoNick;
    private javax.swing.JTextField textoRetorno;
    private javax.swing.JTextField textoTitulo;
    // End of variables declaration//GEN-END:variables
    
    public void cambiarTxtCategoria(String cat){
        this.textoCategoria.setText(cat);
    }

}
