/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Interfaces.IControlador;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author mafiu
 */
public class InterModificarPropuestaCategoria extends javax.swing.JInternalFrame {
    private final InterModificarPropuesta intFrame;
    private final IControlador ic;
    
    /**
     * Creates new form InterModificarPropuestaCategoria
     */
    public InterModificarPropuestaCategoria(IControlador ic, InterModificarPropuesta intFrame) {
        initComponents();
        this.intFrame = intFrame;
        this.ic = ic;
        DefaultMutableTreeNode nodoRaiz = ic.cargarNodoRaizCategorias();
        DefaultTreeModel modeloArbol = new DefaultTreeModel(UtilArbol.construirArbolConPropuestas(nodoRaiz));
        
        this.jTreeCategoria.setModel(modeloArbol);
        this.jTreeCategoria.expandRow(0);
        
        this.botonAceptar.setEnabled(false);
        
        this.setTitle("Elegir Categoria");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeCategoria = new javax.swing.JTree();
        botonCancelar = new javax.swing.JButton();
        textoCat = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();

        jLabel1.setText("Elegir una categoria");

        jTreeCategoria.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeCategoriaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTreeCategoria);

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        textoCat.setText("---");

        jLabel2.setText("Categoria seleccionada:");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoCat)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoCat)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTreeCategoriaValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeCategoriaValueChanged
        // TODO add your handling code here:
        DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) jTreeCategoria.getLastSelectedPathComponent();
        textoCat.setText(nodoSeleccionado.getUserObject().toString());
        if(textoCat.getText().equals("Categoria") || !ic.seleccionaCategoria(nodoSeleccionado.getUserObject().toString())){
            botonAceptar.setEnabled(false);
        }else{
            botonAceptar.setEnabled(true);
        }
    }//GEN-LAST:event_jTreeCategoriaValueChanged

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        
            // TODO add your handling code here:
        this.dispose();
        
        int x = (intFrame.getParent().getWidth() - this.intFrame.getWidth())/2;
        int y = (intFrame.getParent().getHeight() - this.intFrame.getHeight())/2;
        this.intFrame.setLocation(x, y);
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        this.intFrame.cambiarTxtCategoria(this.textoCat.getText());
        this.dispose();
        
        int x = (intFrame.getParent().getWidth() - this.intFrame.getWidth())/2;
        int y = (intFrame.getParent().getHeight() - this.intFrame.getHeight())/2;
        this.intFrame.setLocation(x, y);
    }//GEN-LAST:event_botonAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTreeCategoria;
    private javax.swing.JLabel textoCat;
    // End of variables declaration//GEN-END:variables
}
