/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import Interfaces.IControlador;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author mafiu
 */
public class InterDejarSeguir extends javax.swing.JInternalFrame {

    private final IControlador ic;
    List<String> listaUsuarios;
    /**
     * Creates new form InterDejarSeguir
     * @param ic
     */
    public InterDejarSeguir(IControlador ic) {
        this.ic = ic;
        initComponents();
        listaUsuarios = ic.getUsuarios();
        for(String s : listaUsuarios){
            comboSeguidor.addItem(s);
        }
        this.setTitle("Dejar de Seguir Usuario");
        this.comboDejarSeguir.setEnabled(false);
        this.botonAceptar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelSeguidor = new javax.swing.JLabel();
        comboSeguidor = new javax.swing.JComboBox<>();
        labelDejarSeguir = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        comboDejarSeguir = new javax.swing.JComboBox<>();

        labelTitulo.setText("Elegir usuario seguidor y usuario a dejar de seguir");

        labelSeguidor.setText("Seguidor");

        comboSeguidor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--" }));
        comboSeguidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeguidorActionPerformed(evt);
            }
        });

        labelDejarSeguir.setText("Dejar de Seguir");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        comboDejarSeguir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---" }));
        comboDejarSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDejarSeguirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(labelTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboSeguidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelSeguidor)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboDejarSeguir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelDejarSeguir))))
                        .addGap(0, 55, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSeguidor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboSeguidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(labelDejarSeguir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboDejarSeguir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboSeguidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeguidorActionPerformed
        // TODO add your handling code here:
        int seleccion = comboSeguidor.getSelectedIndex();
        comboDejarSeguir.removeAllItems();
        comboDejarSeguir.addItem("---");
        if(seleccion != 0){
            String seguidor = comboSeguidor.getSelectedItem().toString();
            List<String> listaSeguidos = ic.getSeguidos(seguidor);
            for(String s : listaSeguidos){
                comboDejarSeguir.addItem(s);
            }
            comboDejarSeguir.setEnabled(true);
        }else{
            comboDejarSeguir.setEnabled(false);
            botonAceptar.setEnabled(false);
        }
    }//GEN-LAST:event_comboSeguidorActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        String nick1 = comboSeguidor.getSelectedItem().toString();
        String nick2 = comboDejarSeguir.getSelectedItem().toString();
        ic.dejarSeguirUsuario(nick1, nick2);
        JOptionPane.showMessageDialog(this, nick1 + " ha dejado de seguir a " + nick2 + "!", "Listo!", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void comboDejarSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDejarSeguirActionPerformed
        // TODO add your handling code here:
        int seleccion = comboDejarSeguir.getSelectedIndex();
        if(seleccion != 0){
            botonAceptar.setEnabled(true);
        }else{
            botonAceptar.setEnabled(false);
        }
    }//GEN-LAST:event_comboDejarSeguirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JComboBox<String> comboDejarSeguir;
    private javax.swing.JComboBox<String> comboSeguidor;
    private javax.swing.JLabel labelDejarSeguir;
    private javax.swing.JLabel labelSeguidor;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables

}
