/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Presentacion;

import DataTypes.DataPropuesta;
import Interfaces.IControlador;
import java.awt.Image;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nahud
 */
public class InterConsultaXEstado extends javax.swing.JInternalFrame {
    
    private final IControlador ic;
    private List<String> listaPropuestas = null;
    private List<String> listaEstados;
    private final String[] columnas = {"Colaborador", "Aporte"};
    private DefaultTableModel modelo;
    /**
     * Creates new form InterConsultaXEstado
     */
    public InterConsultaXEstado(IControlador ic) {
        initComponents();
        
        this.ic = ic;
        
        listaEstados = ic.getEstados();
        //listaPropuestas = ic.getPropuestasXEstados();
        
        for(String s : listaEstados){
            comboEstados.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboEstados = new javax.swing.JComboBox<>();
        lblFoto = new javax.swing.JLabel();
        txtNickname = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescrip = new javax.swing.JTextArea();
        txtLugar = new javax.swing.JTextField();
        txtEntrada = new javax.swing.JTextField();
        txt$Necesario = new javax.swing.JTextField();
        txtRetorno = new javax.swing.JTextField();
        txtFechaR = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Lugar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboPropuestas = new javax.swing.JComboBox<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tablaColabx = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtRecaudado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Consulta x Estado");
        setPreferredSize(new java.awt.Dimension(750, 570));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Seleccione Estado :");

        comboEstados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--" }));
        comboEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstadosActionPerformed(evt);
            }
        });

        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        lblFoto.setPreferredSize(new java.awt.Dimension(200, 200));

        txtNickname.setEditable(false);

        txtTitulo.setEditable(false);

        txtEstado.setEditable(false);

        txtDescrip.setEditable(false);
        txtDescrip.setColumns(20);
        txtDescrip.setRows(5);
        jScrollPane1.setViewportView(txtDescrip);

        txtLugar.setEditable(false);

        txtEntrada.setEditable(false);

        txt$Necesario.setEditable(false);

        txtRetorno.setEditable(false);

        txtFechaR.setEditable(false);

        jLabel10.setText("Fecha a realizar :");

        jLabel9.setText("Retorno x colab :");

        jLabel8.setText("$Necesario :");

        jLabel7.setText("Precio x entrada :");

        jLabel5.setText("Descripcion :");

        Lugar.setText("Lugar :");

        jLabel4.setText("Estado :");

        jLabel3.setText("Titulo :");

        jLabel2.setText("Nickname :");

        jLabel6.setText("Seleccione Propuesta:");

        comboPropuestas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--" }));
        comboPropuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPropuestasActionPerformed(evt);
            }
        });

        tablaColabx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Colaborador", "Aporte"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tablaColabx);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jScrollPane8.setViewportView(jPanel4);

        jLabel11.setText("$Recaudado :");

        txtRecaudado.setEditable(false);

        jLabel12.setText("Categoria :");

        txtCategoria.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addComponent(Lugar)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11)
                                .addComponent(jLabel9))
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRetorno)
                            .addComponent(txtRecaudado, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNickname)
                            .addComponent(txtTitulo)
                            .addComponent(txtEstado)
                            .addComponent(jScrollPane1)
                            .addComponent(txtLugar)
                            .addComponent(txtEntrada)
                            .addComponent(txt$Necesario)
                            .addComponent(txtCategoria)
                            .addComponent(txtFechaR, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboPropuestas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(comboPropuestas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lugar))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt$Necesario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtRecaudado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(237, 237, 237)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtFechaR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addComponent(jLabel9))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstadosActionPerformed
        // TODO add your handling code here:
        
            DefaultComboBoxModel<String> modeloB = new DefaultComboBoxModel<>();
            modeloB.addElement("--Seleccionar--");
            comboPropuestas.setModel(modeloB);
            
            this.modelo = new DefaultTableModel(columnas, 0){
            @Override
            public boolean isCellEditable(int row,int column){
                return false; //Evito que las celdas se puedan editar
            }
        };
            
        tablaColabx.setModel(modelo);
        
        if (comboEstados.getSelectedIndex() != 0) {

            int op = comboEstados.getSelectedIndex();
            String estado = comboEstados.getItemAt(op);

            listaPropuestas = ic.getPropXEstado(estado);

            for(String s : listaPropuestas){
                comboPropuestas.addItem(s);
            }
        }else{
            this.lblFoto.setIcon(null);
            this.txtNickname.setText("");
            this.txtTitulo.setText("");
            this.txtEstado.setText("");
            this.txtDescrip.setText("");
            this.txtLugar.setText("");
            this.txtEntrada.setText("");
            this.txt$Necesario.setText("");
            this.txtRetorno.setText("");
            this.txtFechaR.setText("");
            this.txtRecaudado.setText("");
            this.txtCategoria.setText("");
            this.modelo.setRowCount(0);
        }
        
        
       
    }//GEN-LAST:event_comboEstadosActionPerformed

    public boolean abierto(){
        return this.open;
    }
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        this.open = true;
    }//GEN-LAST:event_formComponentShown

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
        this.open = false;
    }//GEN-LAST:event_formComponentHidden

    private void comboPropuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPropuestasActionPerformed
        // TODO add your handling code here:
        int op = comboPropuestas.getSelectedIndex();
        String titulo = comboPropuestas.getItemAt(op);
        List<String> listaAportesColab;

        DataPropuesta DP = null;
        
        this.modelo = new DefaultTableModel(columnas, 0){
            @Override
            public boolean isCellEditable(int row,int column){
                return false; //Evito que las celdas se puedan editar
            }
        };
            
        tablaColabx.setModel(modelo);

        if(!titulo.equals("--Seleccionar--")){
            listaAportesColab = ic.getColabsProp(titulo);
            
            for (String s : listaAportesColab) {
                String[] partes = s.split("\t"); 
                modelo.addRow(new Object[]{partes[0], partes[1]});
            }
            
            DP = ic.consultaDePropuesta(titulo);

            ImageIcon icon = new ImageIcon(DP.getImagen());

            Image imagenEscalada = icon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            lblFoto.setIcon(new ImageIcon(imagenEscalada));

            String retorno = "AMBOS";

            if (DP.getRetorno().toString().equals("ENTRADAS_GRATIS")) {
                retorno = "ENTRADAS GRATIS";
            }
            if (DP.getRetorno().toString().equals("PORCENTAJE_VENTAS")) {
                retorno = "%VENTAS";
            }

            this.txtNickname.setText(DP.getProponente().getNickname());
            this.txtTitulo.setText(DP.getTitulo());
            this.txtEstado.setText(DP.getEstadoActual().getEstado().toString());
            this.txtDescrip.setText(DP.getDescripcion());
            this.txtLugar.setText(DP.getLugar());
            this.txtEntrada.setText(DP.getEntrada().toString());
            this.txt$Necesario.setText(DP.getNecesaria().toString());
            this.txtRetorno.setText(retorno);
            this.txtFechaR.setText(DP.getFechaARealizar().toString());
            this.txtRecaudado.setText(DP.getAlcanzada().toString());
            this.txtCategoria.setText(DP.getCategoria());
        }else{
            this.lblFoto.setIcon(null);
            this.txtNickname.setText("");
            this.txtTitulo.setText("");
            this.txtEstado.setText("");
            this.txtDescrip.setText("");
            this.txtLugar.setText("");
            this.txtEntrada.setText("");
            this.txt$Necesario.setText("");
            this.txtRetorno.setText("");
            this.txtFechaR.setText("");
            this.txtRecaudado.setText("");
            this.txtCategoria.setText("");
            this.modelo.setRowCount(0);
        }

    }//GEN-LAST:event_comboPropuestasActionPerformed

    private boolean open;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lugar;
    private javax.swing.JComboBox<String> comboEstados;
    private javax.swing.JComboBox<String> comboPropuestas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTable tablaColabx;
    private javax.swing.JTextField txt$Necesario;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextArea txtDescrip;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFechaR;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtNickname;
    private javax.swing.JTextField txtRecaudado;
    private javax.swing.JTextField txtRetorno;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
